// <auto-generated />
namespace AssetManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class requiredAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(requiredAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201505121112100_requiredAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
